import styles from './Home.module.css';

export function useHomeStyles() {
  return {
    page: styles.page,
    fadeSection: styles.fadeSection,
    reveal: styles.reveal,
    revealVisible: styles.revealVisible,
    intro: styles.intro,
    carouselStrip: styles.carouselStrip,
    hero: styles.hero,
    left: styles.left,
    right: styles.right,
    choice: styles.choice,
    choiceFlower: styles.choiceFlower,
    choiceContent: styles.choiceContent,
    choicePanel: styles.choicePanel,
    choiceHeader: styles.choiceHeader,
    choiceHeading: styles.choiceHeading,
    choiceSubheading: styles.choiceSubheading,
    choiceButtons: styles.choiceButtons,
    choiceButton: styles.choiceButton,
    entries: styles.entries,
    entriesMain: styles.entriesMain,
    entriesHeader: styles.entriesHeader,
    entriesTitle: styles.entriesTitle,
    entriesList: styles.entriesList,
    entryCard: styles.entryCard,
    entryTypePill: styles.entryTypePill,
    entryTitle: styles.entryTitle,
    entryPreview: styles.entryPreview,
    entryMeta: styles.entryMeta,
    entryDate: styles.entryDate,
    entriesFooter: styles.entriesFooter,
    entriesLink: styles.entriesLink,
    closing: styles.closing,
    closingInner: styles.closingInner,
    closingText: styles.closingText,
    closingSignature: styles.closingSignature,
    headlineCarousel: styles.headlineCarousel,
    headlineTrack: styles.headlineTrack,
    headlineRow: styles.headlineRow,
    kicker: styles.kicker,
    heading: styles.heading,
    line: styles.line,
    italic: styles.italic,
    body: styles.body
  };
}

