import styles from './Home.module.css';

export function useHomeStyles() {
  return {
    page: styles.page,
    fadeSection: styles.fadeSection,
    reveal: styles.reveal,
    revealVisible: styles.revealVisible,
    intro: styles.intro,
    hero: styles.hero,
    left: styles.left,
    skillPills: styles.skillPills,
    skillPill: styles.skillPill,
    choice: styles.choice,
    choiceFlower: styles.choiceFlower,
    choiceContent: styles.choiceContent,
    choicePanel: styles.choicePanel,
    choiceHeader: styles.choiceHeader,
    choiceHeading: styles.choiceHeading,
    choiceSubheading: styles.choiceSubheading,
    choiceButtons: styles.choiceButtons,
    choiceCta: styles.choiceCta,
    entries: styles.entries,
    entriesMain: styles.entriesMain,
    entriesHeader: styles.entriesHeader,
    entriesTitle: styles.entriesTitle,
    entriesList: styles.entriesList,
    entryCard: styles.entryCard,
    entryTypePill: styles.entryTypePill,
    entryTitle: styles.entryTitle,
    entryPreview: styles.entryPreview,
    entryMeta: styles.entryMeta,
    entryDate: styles.entryDate,
    entriesFooter: styles.entriesFooter,
    entriesLink: styles.entriesLink,
    headlineCarousel: styles.headlineCarousel,
    headlineTrack: styles.headlineTrack,
    headlineRow: styles.headlineRow,
    kicker: styles.kicker,
    kickerRole: styles.kickerRole,
    kickerDot: styles.kickerDot,
    kickerLocation: styles.kickerLocation,
    heading: styles.heading,
    nameStack: styles.nameStack,
    nameRow: styles.nameRow,
    nameFlower: styles.nameFlower,
    nameBody: styles.nameBody,
    line: styles.line,
    italic: styles.italic,
    body: styles.body,
  };
}
