import { useMemo } from 'react';

import styles from './WorkDashboard.module.css';

export function useWorkDashboardStyles() {
  return useMemo(
    () => ({
      layout: styles.layout,
      sidebar: styles.sidebar,
      sidebarNav: styles.sidebarNav,
      sidebarLink: styles.sidebarLink,
      sidebarLinkActive: styles.sidebarLinkActive,
      main: styles.main,
      screen: styles.screen,
      screenScroller: styles.screenScroller,
      topControls: styles.topControls,
      controlsRow: styles.controlsRow,
      activeTitle: styles.activeTitle,
      controlsActions: styles.controlsActions,
      buttonLink: styles.buttonLink,
      pageEnter: styles.pageEnter,
      contentEnter: styles.contentEnter,
      sectionFrame: styles.sectionFrame,
      sectionFrameCenter: styles.sectionFrameCenter,
      sectionLeaving: styles.sectionLeaving,
      sectionEntering: styles.sectionEntering,
      section: styles.section,
      sectionTitle: styles.sectionTitle,
      sectionBody: styles.sectionBody,
      stackTight: styles.stackTight,
      overviewSectionBody: styles.overviewSectionBody,
      overviewLeft: styles.overviewLeft,
      overviewIntroWrap: styles.overviewIntroWrap,
      overviewRightStack: styles.overviewRightStack,
      highlightsGrid: styles.highlightsGrid,
      highlightTile: styles.highlightTile,
      highlightTileButton: styles.highlightTileButton,
      highlightLine: styles.highlightLine,
      highlightLineEnd: styles.highlightLineEnd,
      highlightChevron: styles.highlightChevron,
      currentPill: styles.currentPill,
      contactCard: styles.contactCard,
      contactStack: styles.contactStack,
      contactRow: styles.contactRow,
      iconBadge: styles.iconBadge,
      contactRowText: styles.contactRowText,
      contactCta: styles.contactCta,
      overviewCards: styles.overviewCards,
      signalGrid: styles.signalGrid,
      signalItem: styles.signalItem,
      contactGrid: styles.contactGrid,
      contactItem: styles.contactItem,
      contactKey: styles.contactKey,
      contactLinkSubtle: styles.contactLinkSubtle,
      panel: styles.panel,
      panelHeading: styles.panelHeading,
      panelStack: styles.panelStack,
      summary: styles.summary,
      body: styles.body,
      kv: styles.kv,
      kvLabel: styles.kvLabel,
      kvValue: styles.kvValue,
      contactLink: styles.contactLink,
      list: styles.list,
      item: styles.item,
      itemHeader: styles.itemHeader,
      itemTitle: styles.itemTitle,
      itemMeta: styles.itemMeta,
      bullets: styles.bullets,
      featuredPanel: styles.featuredPanel,
      pubLink: styles.pubLink,
      emptyState: styles.emptyState,
    }),
    []
  );
}

