import { useMemo } from 'react';

import styles from './WorkDashboard.module.css';

export function useWorkDashboardStyles() {
  return useMemo(
    () => ({
      layout: styles.layout,
      sidebar: styles.sidebar,
      sidebarNav: styles.sidebarNav,
      sidebarLink: styles.sidebarLink,
      sidebarLinkActive: styles.sidebarLinkActive,
      main: styles.main,
      screen: styles.screen,
      screenScroller: styles.screenScroller,
      topControls: styles.topControls,
      controlsRow: styles.controlsRow,
      activeTitle: styles.activeTitle,
      controlsActions: styles.controlsActions,
      buttonLink: styles.buttonLink,
      pageEnter: styles.pageEnter,
      contentEnter: styles.contentEnter,
      stagger: styles.stagger,
      sectionFrame: styles.sectionFrame,
      sectionFrameCenter: styles.sectionFrameCenter,
      sectionLeaving: styles.sectionLeaving,
      sectionEntering: styles.sectionEntering,
      section: styles.section,
      sectionBody: styles.sectionBody,
      body: styles.body,
      list: styles.list,
      item: styles.item,
      itemHeader: styles.itemHeader,
      itemTitle: styles.itemTitle,
      itemMeta: styles.itemMeta,
      eduPrimary: styles.eduPrimary,
      bullets: styles.bullets,
      featuredPanel: styles.featuredPanel,
      projectsFlow: styles.projectsFlow,
      featuredProject: styles.featuredProject,
      featuredHeader: styles.featuredHeader,
      featuredKicker: styles.featuredKicker,
      featuredTitle: styles.featuredTitle,
      featuredMeta: styles.featuredMeta,
      featuredOverview: styles.featuredOverview,
      featuredMain: styles.featuredMain,
      featuredBlocks: styles.featuredBlocks,
      featuredBlock: styles.featuredBlock,
      blockLabel: styles.blockLabel,
      blockList: styles.blockList,
      featuredMedia: styles.featuredMedia,
      featuredImage: styles.featuredImage,
      featuredImagePlaceholder: styles.featuredImagePlaceholder,
      explorations: styles.explorations,
      explorationsHeader: styles.explorationsHeader,
      explorationsTitle: styles.explorationsTitle,
      explorationsIntro: styles.explorationsIntro,
      explorationList: styles.explorationList,
      explorationItem: styles.explorationItem,
      explorationHeader: styles.explorationHeader,
      explorationTitle: styles.explorationTitle,
      explorationMeta: styles.explorationMeta,
      explorationDesc: styles.explorationDesc,
      explorationDetails: styles.explorationDetails,
      explorationSummary: styles.explorationSummary,
      explorationPoints: styles.explorationPoints,
      pubSection: styles.pubSection,
      pubLayout: styles.pubLayout,
      pubContent: styles.pubContent,
      pubMedia: styles.pubMedia,
      pubImage: styles.pubImage,
      pubLink: styles.pubLink,
      skillsGrid: styles.skillsGrid,
      skillCard: styles.skillCard,
      skillCardHeader: styles.skillCardHeader,
      skillCardTitle: styles.skillCardTitle,
      skillCardSubtitle: styles.skillCardSubtitle,
      skillCardTags: styles.skillCardTags,
      skillTag: styles.skillTag,
      skillCardBody: styles.skillCardBody,
      cfWrap: styles.cfWrap,
      cfBlock: styles.cfBlock,
      cfLabel: styles.cfLabel,
      courseList: styles.courseList,
      courseItem: styles.courseItem,
      courseTopRow: styles.courseTopRow,
      courseName: styles.courseName,
      courseProvider: styles.courseProvider,
      courseFocus: styles.courseFocus,
      emptyState: styles.emptyState,
    }),
    []
  );
}
